### ISSUE TITLE
MQTT Password

### ISSUE THREAD

**Issue by dkcsn** [alexander-vitishchenko/hc3-to-mqtt#1]
Thank you for coding this interesting QA.
I was wondering if its possible to use MQTT servers with Username/password protection?

could you elaborate om the 
hc3Auth - login and password for pulling events from Fibaro HC3. Must be encoded with Base64, e.g. "admin:password" -> "YWRtaW46cGFzc3dvcmQ="

hc3Auth _ is the the HC3 admin password i need to base64 encode, not sure what is ment here. 

And the IP for MQTT is for an external MQTT server - right ?

**Comment by alexander-vitishchenko** [comment]
Sure, I'll add support for MQTT authentication tomorrow, it is on my roadmap already.

This is how "hc3Auth" and "mqttUrl" look like at my setup:
![image](https://user-images.githubusercontent.com/1070777/107926657-a6cdce00-6f7e-11eb-917c-a66f2cc40e1b.png)

1) "hc3Auth" variable stores both username and password, same way as [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) encodes user credentials => you take your username, then append it with ":" character, then append with password, and then encode the resulting String with [Base64](https://www.base64encode.org/). 

I could store username and password in two separate variables (plain text), but because those variables are maintained at GUI - it felt right to use [Base64 encoding](https://www.base64encode.org/) and improve a sense of security slightly. This is not something what everyone need, and is mostly aiming to protect you while browsing QA settings in front of other people, reducing risk of exposing a sensitive information
 
2) "mqttUrl" is a standard MQTT connection URL.  MQTT broker host could be addressed by internal/external IP or DNS. Just need to make sure this IP/DNS is addressable from your Fibaro Home Center 3.

I personally use Mosquitto MQTT broker within my home network, as you can see on the screen address (IP address class C). I also tried to use MQTT broker in cloud, but it has a limited number of use cases for my setup, so I decided to stay with a local one for now.

Please let me know if this description helps, and I can probably move it to the home page.

**Comment by dkcsn** [comment]
i think I got it :-) 
Username admin
i will wait for the update with U/P for MQTT :-) - i use Mosquitto MQTT broker as well
Password = Password 
admin:password will be YWRtaW46cGFzc3dvcmQ=
using CyberChef ;-)

**Comment by dkcsn** [comment]
local function connect()
        local status, data = pcall(mqtt.Client.connect, mqttUrl, {clientId="HC3-"..plugin.mainDeviceId, username = 'user', password = 'Pass',
            keepAlivePeriod=keepAlivePeriodSeconds, lastWill={topic='test/last_will', payload=os.date()}})
        if status then
            self.client=data
            self.client:addEventListener('published', function(event) self:onPublished(event) end)  
            self.client:addEventListener('message', function(event) self:onMessage(event) end)
            self.client:addEventListener('connected', handleConnect)
            self.client:addEventListener('subscribed', function(event) self:debug('subscribed: '..json.encode(event)) end)
            self.client:addEventListener('error', handleError)
        else
            self:debug("connect error: "..data)
            fibaro.setTimeout(retryMilliSeconds, connect)
        end
    end

**Comment by alexander-vitishchenko** [comment]
Added additional QuickApp variables to control MQTT connection parameters:
   * mqttAuth to setup user credentials in Base64 encoded form
   * mqttUsername and mqttPassword to setup user credentials in plain text
   * mqttClientId to setup custom client id, or using **"HC3-" .. plugin.mainDeviceId** by default
   * mqttKeepAlive to setup custom MQTT Keep Alive Period

I should add pcall wrapper around MQTT connect function as you suggested => introduce an additional layer of error handling/protection... but then I somehow started thinking on how Fibaro may possibly implement their MQTT connectivity lib... would it be possibly to cause a race condition issue when MQTT connection is failed, and their lib reports same issue with both pcall and "error" callback function, resulting in 2 simultaneous MQTT reconnect attempts :)

**Comment by dkcsn** [comment]
I downloaded the new version - its Corrupted or something else is wrong. When changing the variables - HC3 shows an error with red - "cannot save". Old version works. I tried download again - try all over, but i cant save/change the variables. actually i have never seen this error in HC3 before,
