### ISSUE TITLE
Fibaro FGT-001 Radiator TRV support

### ISSUE THREAD

**Issue by MomosX** [alexander-vitishchenko/hc3-to-mqtt#16]
Hi,

attached are the json files from the Fibaro FGT-001, parent and 3 childs.  Please see if you can impement it :) I would send one but can't take it out from my installation.
Thank you !
[FGT-001.zip](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/7919887/FGT-001.zip)

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX

Can you please prioritize what thermostats take the most priority for you, if choosing between Fibaro FGT-001, Danfoss LC13 TRV Support, and Danfoss RoomSensor Thermostat?

**Comment by MomosX** [comment]
Used the fix described here https://github.com/alexander-vitishchenko/hc3-to-mqtt/issues/31 and it works now.

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX - just to clarify, are you sure #31 works for you?

It might be fine as a temporary workaround, but the solution is not merged to the GitHub, meaning that you have to apply/merge the #31 solution everytime after downloading the QuickApp from the GitHub.

+ the reason I didn't at that extra line of code to Thermostat.isSupported is because new thermostat type aliases are intended to be added with a different approach, using fibaroTypeOverride + wildcards for more stability and performance

**Comment by MomosX** [comment]
It works yes, but i have modified the files like i described in the other topic..  Sorry, i'm not familiarised with how this github works , hence why i asked if you added the changes for thermostats in the QA file.  

I undertand the reason now why you did not added it yet, so i'll remember to merge the workaround in the file until then :)

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX - can you please check if the latest version of the QuickApp works for your thermostats?

**Comment by MomosX** [comment]
works only if i modify:

```
function Thermostat.isSupported(fibaroDevice)
    if (fibaroDevice.type == "com.fibaro.hvacSystem" or fibaroDevice.type == "com.fibaro.FGT001" or fibaroDevice.type == "com.fibaro.thermostatDanfoss") then 
        return true 
    else 
        return false
    end
end
```

These devices

**Comment by alexander-vitishchenko** [comment]
Hi @MomosX can you please advise if you are using the latest QuickApp version, and share full logs?

**Comment by alexander-vitishchenko** [comment]
Closed as expired, and need more inputs to confirm the issue exist and then fix it
