### ISSUE TITLE
not a issue just ask

### ISSUE THREAD

**Issue by Bedo92ali** [alexander-vitishchenko/hc3-to-mqtt#19]
if I want to connect directly to the room assistant without the home assistant can this QA do it?

**Comment by alexander-vitishchenko** [comment]
Hi @Bedo92ali 

This QuickApp does only support Home Assistant and Homie (experimental) MQTT conventions 

It should be feasible to add support for Room Assistant MQTT convention due to the modular architecture of the Quick App. If you can do Lua coding then I can merge your code to this QuickApp

…I’d be happy to implement it myself, but I’m not sure if Room Assistant has enough RIO by comparison to adding new features to the Home Assistant integration, it is a bit time consuming and I have other feature request in the list like adding new thermostats support and so on

**Comment by Bedo92ali** [comment]
I will try it and I will back to you

**Comment by alexander-vitishchenko** [comment]
Few hints:
  - you can add new MQTT convention by editing mqtt_convention_api.lua, and implementing new logic by inheriting from MqttConventionPrototype (using the existing Homie implementation as a basic reference), and registering your new implementation at mqttConventionMappings
  - then switching to QuickApp configuration page and editing QuickApp variable “mqttConvention” to get your new MQTT convention enabled

Feel free to contact me for consulting via GitHub or Discord
