### ISSUE TITLE
Changing the 'mqtt-convention' crashes the QA.

### ISSUE THREAD

**Issue by jandejongh** [alexander-vitishchenko/hc3-to-mqtt#27]
Changing the 'mqtt-convention' [from 'home-assistant'] crashes the QA.
There appear to be some hard-coded assumptions on the value of this variable.

**My assumption:** This variable sets the MQTT topic prefix. [And I don't use Home Assistant...]

But hey, **Слава Україні!** and hoping for better times for you! And thanks so much for this QA. I can provide more details if needed once you're back up and running safe and sound.

**Comment by alexander-vitishchenko** [comment]
Hi @jandejongh!

"mqttConvention" variable is about choosing the MQTT integration type, like HC3 <-> Home Assistant, or HC3 <-> Homie.

This variable accepts only the following values at the moment:
1. "home-assistant" to enable Home Assistant MQTT - https://www.home-assistant.io/integrations/mqtt/
2. "homie" to enable POC (prove of concept) grade implementation for Homie MQTT specification - https://homieiot.github.io/
3. "debug" - placeholder for custom/developer needs in the future

So yes, "mqttConvention" does indirectly influence MQTT topic prefix, but there is no direct control given through QuickApp variable, because Home Assistant and Homie specifications force me to use "homeassistant" and "homie" prefixes respectively.

I'd suggest to stick to Home Assistant MQTT convention even if you don't use Home Assistant, because is the most comprehensive mqtt convention implementation for our QuickApp. It has some "bells and whistles" you may not need, but at the same time you can simple ignore the events/attributes you don't need.

If Home Assistant MQTT convention is something what doesn't work for you for any reason... the alternative would be to try Homie specification, as it seems to be vendor agnostic, but also the current implementation is limited in functionality. Another alternative would be to extend "debug" implementation to render all HC3 events to MQTT without any translation of the data model.

Let me know your exact needs and we see what implementation approach would be the best fit.

Thank you!
Alexander

P.S.: apologies for late reply as I only finished my accommodation in Berlin

**Comment by alexander-vitishchenko** [comment]
Not a bug / expected behavior

MQTT prefixes are predefined by Home Assistant & Homie specifications. Using customer prefixes are possible with custom MQTT implementation if there is no way to rely on standard implementation
