### ISSUE TITLE
Rooms are not imported as area

### ISSUE THREAD

**Issue by EzequielPitton78** [alexander-vitishchenko/hc3-to-mqtt#28]
Rooms are not currently imported as area in HomeAssistant. For big installs with 100's of devices would be very convenient

**Comment by alexander-vitishchenko** [comment]
Hi @EzequielPitton78 

Yes - importing areas/rooms would be a great feature. 

Unfortunately, Home Assistant MQTT Discovery doesn't allow exposing area/room information for devices, which is why it is not implemented. 

You can check the details by yourself, and let me know if it's not the case so I can add it to HC3 <-> HA integration https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by alexander-vitishchenko** [comment]
Not able to implement via Home Assistant MQTT specification, while the request itself totally makes sense from a user perspective

**Comment by alexander-vitishchenko** [comment]
Hi @EzequielPitton78 

UPDATE: I could partially implement Fibaro room/area names import to Home Assistant

1. This requires Home Assistant to have areas created upfront, and their names to be in sync with Fibaro HC3
2. Home Assistant MQTT Discovery specification supports area names import for parent device, and I didn't see support for individual child entities. It should work for the majority of cases, assuming parent device and child entities are located in the same area/room
