### ISSUE TITLE
elero blinds and shutters support

### ISSUE THREAD

**Issue by Mikl-h** [alexander-vitishchenko/hc3-to-mqtt#47]
Hi, can you please add support for elero venetian blinds and roller shutters? They behave a bit differently than already coded covers.

These devices advertise their state as string ("Unknown", "Opened", "Closed", "Opening", "Closing", "FavoritePosition1", "FavoritePosition2")
They don't respond to setValue command but to: "open", "close", "stop" and "setFavoritePosition" with additional argument "FavoritePosition1" or "FavoritePosition2".
There are three more commands which are not really needed: "rotateSlatsUp", "rotateSlatsDown", "stopSlats"

[response_1677794384428.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10876493/response_1677794384428.txt)
[response_1677794146086.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10876494/response_1677794146086.txt)

**Comment by rudi70** [comment]
If you implement it.... you'll get a coffee ;-) (Donation)

**Comment by Mikl-h** [comment]
I am not using HC3 but Yubii Home, but it should work the same.
I have attached JSON, Yubbi log and part of device_api file which I modified to work with elero devices. It's lines 315-346, everything else is untouched.
It does only basic commands (open, close, stop). I don't understand HA or Fibaro enough to implement more (favorite positions or position feedback).

[mqtt-4090669a989041fe15642759cafe0e5a-Pravá-b08d729ab5d96ccfb6e6bf230f9163bc.json.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10998920/mqtt-4090669a989041fe15642759cafe0e5a-Prava-b08d729ab5d96ccfb6e6bf230f9163bc.json.txt)
[device_api.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10998921/device_api.txt)
[Yubii home.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10998923/Yubii.home.txt)
![obrazek](https://user-images.githubusercontent.com/46164661/225842534-2c3abe43-b66e-4283-a667-2c7053f3bd04.png)

**Comment by alexander-vitishchenko** [comment]
Hi @Mikl-h,

Thank for context and trying to look into the QuickApp source code, this is much appreciated especially if you want to help in the future.

1) You have added "com.fibaro.actor" type as the criterion for Elero blinds/shutters device identification. The problem with the proposed approach is about using a generic value that is also applicable for other device types. Therefore it would break the functionality for other users, and even for yourself. For example, one of your switches is now wrongly identified as "cover-default". How can you control a switch (or other device types) with a Cover/Shutter? 

> <📦> #55 named as "HC3 <-> MQTT Bridge" in "Obývák" room identified as **cover-default** type

2) Can you please provide full JSON for devices 34 and 37 that I was asking earlier? This will help me understand how device identification should work properly. Feel free to share JSON for more devices if they have different types, and so I can implement its support properly
3) Did you try using the position slider at Home Assistant, and at Yubii Home - does it mirror the changes between systems? 
4) Or you only used "open", "close", "stop"?

**Comment by Mikl-h** [comment]
Hi @alexander-vitishchenko 

1. I know "com.fibaro.actor" is not ideal, it was just a quick fix to get it working as I don't have any other devices than elero paired with Yubii. I will try other criteria when I get home.
2. Do you need JSON export from HA or Yubii/HC3?
3. Position slider is broken as elero devices don't advertise their position as 0-100 but as either of these values: "Unknown", "Opened", "Closed", "Opening", "Closing", "FavoritePosition1", "FavoritePosition2"
4. I only use "open", "close", "stop". I just started with HA and lack the knowledge to add a switch entity to device in HA to send other commands, e.g. "setFavoritePosition"

**Comment by alexander-vitishchenko** [comment]
1. The existing identification criteria should be fine, with no adjustments required for you device 35 as I see in logs. The reason your Elero shutter didn't work is because there was only "positioning" support implemented, with no "open", "close", "stop".

Please check the new experimental version that I've implemented over weekend, with a broader action list support for your device id 35. As I do not have any Elero devices - need your to do the testing and provide me with a report :-)

2. Can you please send me few more JSON files like for device 35 ([response_1677794384428.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/10876493/response_1677794384428.txt)), describing the data for the shutter (id 35) in "Open" and "Stopped" states? (your example is for "Closed" state)

3. As for parent devices - they are mostly used for device aggregation and useful people who work on various systems integrations like me, but we hopefully don't need to deal with it for your feature request.

**Comment by alexander-vitishchenko** [comment]
Hi @Mikl-h have you had a chance to test the latest version of the quick app and see if it supports open/close/stop commands from Home Assistant UI?

**Comment by alexander-vitishchenko** [comment]
Hi @Mikl-h, @rudi70,

Can you please check the latest version of the QuickApp and let me know if it works for you?

**Comment by rudi70** [comment]
Hi! sorry.... I move to a new flat and so I can support you with data in round about 1 week..... at the first trail I can't verify it :-(

**Comment by Surycx** [comment]
Hi @alexander-vitishchenko you verified the elero product with 
`elseif self:fibaroDeviceHasAction("rotateSlatsUp") or self:fibaroDeviceHasAction("rotateSlatsDown") or self:fibaroDeviceHasAction("stopSlats") then` (device_api, line 347)
and then use 
`msg.tilt_command_template = "{% if value == 0 %}rotateSlatsDown{% elif value == 100 %}rotateSlatsUp{% else %}unsupportedByDeviceAndHomeAssistant{% endif %}"` in mqtt_convention_api, line 309

These functions are not what @Mikl-h wanted to use IIRC. The functions/actions should be "setFavoritePosition","FavoritePosition1"  or ""setFavoritePosition","FavoritePosition2"  instead of rotateSlatsUp/Down
The fibaro command for this is `hub.call(deviceID, "setFavoritePosition","FavoritePosition1")`


I changed my device_api and mqtt_convention_api files for using the FavoritePositions like this:

In device_api I added this after line 69:
```
elseif propertyName == "actionp" then
        print("FUNCTION CALL: \"" .. propertyName .. "\", with PARAMS \"" .. json.encode(params) .. "\" for device #" .. self.id)
        fibaro.call(self.id, params[1], params[2])
```

In mqtt_convention_api I changed lines 308 and 309 to this:
```
msg.tilt_command_topic = self:setterTopic(haEntity, "actionp")
msg.tilt_command_template = "{% if value == 0 %}setFavoritePosition,FavoritePosition1{% elif value == 100 %}setFavoritePosition,FavoritePosition2{% else %}unsupportedByDeviceAndHomeAssistant{% endif %}"
```

[device_api.txt](https://github.com/alexander-vitishchenko/h
[mqtt_convention_api.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/11945700/mqtt_convention_api.txt)
c3-to-mqtt/files/11945698/device_api.txt)

I tested it and it sends the right commands to the elero device.

The only I have atm is that after I used for example "setFavoritePosition2" I can only use any other button until I use "setFavoritePosition1" to use "setFavoritePosition2" again.
As you can see the right arrow isn't enabled. Is this and HA issue or coming from the binding?
![image](https://github.com/alexander-vitishchenko/hc3-to-mqtt/assets/83983725/f0469634-a08b-471e-8550-efb2f83af448)

**Comment by alexander-vitishchenko** [comment]
Let me look at it during the weekend and thank you for more inputs, the more the better, you know :)

**Comment by Surycx** [comment]
@alexander-vitishchenko another thing what comes in mind is, if its possible to show the state of the elero device in HA correctly...you get the state from `hub.get(deviceID,"state")` within the homecenter or from the api within the `device.properties.state`
If you need more information, I will try to provide as many as possible :-)

**Comment by alexander-vitishchenko** [comment]
Hi @Surycx, @Mikl-h,

I've recently posted the new QuickApp version 1.0.232, can you please look at it and tell if Home Assistant shows Open/Closed states properly now?

**Comment by Surycx** [comment]
At first with the elero device I tested only Opening/Closing/Closed worked.
I had to append line 376 to 393 in the device.api
[device_api.txt](https://github.com/alexander-vitishchenko/hc3-to-mqtt/files/12240195/device_api.txt)

With this Opening/Opened/Closing/Closed works. 
Unknown position/state isn't working for me.

Additionally if I press stop in HA the state of the device isn't updated (to unknown im somewhere in the middle).

**Comment by alexander-vitishchenko** [comment]
HI @Surycx 

The "Unknown" state is expected to be omitted while HC3 => HA event transmission, i.e. I'd expect no "Unknown" state to be seen in MQTT.

Please let me know if you use the latest 1.0.232 version of the QuickApp as is, or made local changes to it? (it would be great to see the changes in diff format)

**Comment by Surycx** [comment]
@alexander-vitishchenko 

What diff format do you want the changes to be in?

1. **First I used the QA as it is:**

Only Closing, Closed and Opening worked fine. When the shutter is Opened the state on HA didn't change.

2. **Second I changed the function Cover:overrideCustomFibaroEventIfNeeded in device.api to:**

```
function Cover:overrideCustomFibaroEventIfNeeded(originalEvent)
    
    --[[if originalEvent.data.property == "state" and originalEvent.data.newValue == "Unknown" then
        return nil -- no event to be emitted HC3 => HA
    end]]
	
    -----------------------------ADDED BY SURYCX---------------------------------------------
    if originalEvent.data.property == "state" then
        local value = originalEvent.data.newValue
        local newStateEvent
        if value == "Closed" then
            -- generate additional event for indicating cover state
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateClosed)
        elseif value == "Opened" then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateOpen)
        elseif value == "Closing" then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateClosing)
        elseif value == "Opening" then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateOpening)
        else
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateUnknown)
        end
        
        return { originalEvent, newStateEvent }
    end
	-----------------------------END ADDED BY SURYCX-------------------------------------------
	
    if originalEvent.data.property == "value" then
        local value = originalEvent.data.newValue
        local newStateEvent
        if value == 0 then
            -- generate additional event for indicating cover state
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateClosed)
        elseif value >= 99 then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateOpen)
        elseif value < 50 then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateClosing)
        elseif value >= 50 then
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateOpening)
        else
            newStateEvent = createFibaroEventPayload(self.sourceDeviceNode.fibaroDevice, "state", Cover.stateUnknown)
        end
        
        return { originalEvent, newStateEvent }
    end

    return originalEvent
end
```

Now Opened as state works too!

3. Accounting the "Unknown" state. An elero device sends back "Unknown" if it is in between upper and lower endposition because it has no absolute values.
When I use my changed device_api and I press stop the topic:
**fibaro => home assistant/state** in MQTT is changed to the correct state:
`{
  "timestamp": "Thu Aug  3 07:23:46 2023",
  "created": 1691040226,
  "value": "Unknown",
  "roomName": "Testing",
  "id": 39,
  "deviceName": "JA_Test"
}`
Is it possible that this Unknown is shown in HA?

**Comment by alexander-vitishchenko** [comment]
Can you please share the MQTT state event when Cover gets to the opened state, for the original 1.0.232?

I suspect Fibaro uses Open and Opened aliases depending if this is Z-Wave or Elero/Nice. If this is true - then I can implement it so it could be used by anyone else with and with less lines of code.

**Comment by Surycx** [comment]
@alexander-vitishchenko Here is the MQTT state event (homeassistant/cover/39/events/fibaro => home assistant/state): `{"timestamp":"Mon Aug  7 06:58:20 023","id":39,"deviceName":"JA_Test","roomName":"Testing","value":"Opened","created":1691384300}`
`{"timestamp":"Mon Aug  7 06:57:54 2023","id":39,"deviceName":"JA_Test","roomName":"Testing","value":"Opening","created":1691384274}`
Tested with the original 1.0.232

**Comment by alexander-vitishchenko** [comment]
Done for the new 1.0.233 version
